# Generated by Django 5.0 on 2023-12-12 23:36

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_tag_options_tag_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg']), post.models.validate_file_size]),
        ),
    ]
