# Generated by Django 5.0 on 2023-12-13 00:04

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), post.models.validate_file_size]),
        ),
    ]
